### PR TITLE
CDP-1877: Write graphic update resolvers

### PR DESCRIPTION
**Pull request by edwinmah**
* Added graphic resolvers
* Added a `title` field to the `ImageFile` type because the graphic files form will need to save a title.
* Made the `copyright` field return a `Copyright` enum instead of a string. I also considered a boolean but decided than an enum would allow for additional values in case that's desired in the future.
* Added various resolver tests
* Will need to run `prisma deploy` because of the model changes described above.

### CODE REVIEW

**Comment by terriregan** [comment]
The one thing that I think we should continue to do is create a 'Graphic' folder in the resolvers directory in the same way that Package was added and then creating a index.js, controller.js (if necessary) and the applicable test file.  Thoughts?

**Comment by edwinmah** [comment]
I don't have any issues with having a Graphic folder. Do you it me to do it just for Graphic or for all of the resolver types, e.g., Bureau, Document, etc.?

**Comment by terriregan** [comment]
Given our tight timeline and how busy you are, just move the Graphic and if possible, move the Package test into Package folder (of course, if you find yourself with enough time, feel free to move the other stuff --I just started piecemeal )

**Comment by edwinmah** [comment]
Just moved them to their own directories. I left in place the ones without tests.

**Pull request merged**
